inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - db/**/*
    - bin/**/*
    - spec/features/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/support/chosenjs.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/active_admin.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - node_modules/**/*
    - config/initializers/devise.rb

RSpec:
  Exclude:
    - spec/system/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - config/environments/*

Layout/LineLength:
  Exclude:
    - app/admin/**/*

# New cops configuration
Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true
